name: state_repository
description: Manage State without create Widgets on the tree,
 the widgets sign for notificationchanges 
 then the repository notify the Widget do rebuild when data changes,
 repositories can be shared easily across widgets.
version: 1.0.0
homepage: https://github.com/petrusje/staterepository

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
